Haber_Sitesi_Proje/main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Haber_Sitesi_Proje/news/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

Haber_Sitesi_Proje/main/models.py
from django.db import models
# Admin tarafında haberin editlenmesi 'ckeditor' tarafından sağlanıyor.
from ckeditor.fields import RichTextField
class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Kategoriler'

    def __str__(self):
        return self.title

# Haber Model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='imgs/')
    detail=RichTextField()
    add_time=models.DateTimeField(verbose_name='Yayımlanma Tarihi')

    class Meta:
        verbose_name_plural='Haberler'
        # Paylaşılan haberin öne çıkması "ordering=['-add_time']"
        ordering=["-add_time"]
    def __str__(self):
        return self.title


# Yorumlar
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

Haber_Sitesi_Proje/main/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import News, Category,Comment
def home(request):
    first_news=News.objects.first()
    three_news=News.objects.all()[1:3]
    three_categories=Category.objects.all()[0:3]
    return render(request,'home.html',{
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })

# Tüm haberler
def all_news(request):
    all_news=News.objects.all()
    return render(request,'all-news.html',{
        'all_news':all_news
    })

# Detay Sayfası
def detail(request,id):
    news=News.objects.get(pk=id)
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        comment=request.POST['message']
        Comment.objects.create(
            news=news,
            name=name,
            email=email,
            comment=comment
        )
        messages.success(request,'Comment submitted but in moderation mode.')
    category=Category.objects.get(id=news.category.id)
    rel_news=News.objects.filter(category=category).exclude(id=id)
    comments=Comment.objects.filter(news=news,status=True).order_by('-id')
    return render(request,'detail.html',{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })

# Tüm kategoriyi getir

def all_category(request):
    cats=Category.objects.all()
    return render(request,'category.html',{
        'cats':cats
    })


# Tüm kategoriyi getir

def category(request,id):
    category=Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    return render(request,'category-news.html',{
        'all_news':news,
        'category':category
    })

Haber_Sitesi_Proje/main/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Tüm Haberler</h3>
    <!-- Haber Kutusu -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	<div class="row no-gutters" onclick="location.href='/detail/{{news.id}}'">
	    <div class="col-md-3">
        <a href="/detail/{{news.id}}"><img src="/media/{{news.image}}" class="card-img-top-all" alt="{{news.title}}"></a>
	    </div>
	    <div class="col-md-8">
	      <div class="card-body-y">
	        <h4 class="card-title">{{news.title}}</h4>
	        <p class="card-text">{{news.detail|safe}}</p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

Haber_Sitesi_Proje/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Anasayfa{% endblock %}</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/test.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<body>
	<!-- Önemli Haberler -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">HABERDAR.COM</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Anasayfa</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-news' %}">Tüm Haberler</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-category' %}">Kategori</a>
		      </li>
		    </ul>
		  </div>
	  	</div>
    </nav>
    
    {% block content %}
	{% endblock %}

<hr/>
<footer class="page-footer">
  <div class="footer-copyright text-center py-3">Doğukan Oygur © 2021 Copyright.
    <a href="http://127.0.0.1:8000/" style="text-decoration: none"> HABERDAR.COM</a>
  </div>
</footer>
</body>
</html>

Haber_Sitesi_Proje/main/templates/category-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- Haber Kutusu -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
        <a href="/detail/{{news.id}}" ><img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}"></a>
	    </div>
	    <div class="col-md-8">
	      <div class="card-body-t">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail|safe}}</p>
	        <p class="card-text"><small class="text-muted">{{news.add_time}}</small></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

Haber_Sitesi_Proje/main/templates/category.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Tüm Kategoriler</h3>
	<div class="row">
		<!-- Kategori Kutusu -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <a href="category/{{cat.id}}" ><img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

Haber_Sitesi_Proje/main/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- Öne Çıkan Haberler -->
	<div class="row my-3">
		<!-- Sol taraf -->
		<div class="col-md-8">
			<div class="card mb-3">
			  <div class="card-body">
			    <h2 class="card-title"><b>{{news.title}}</b></h2>
			    <p class="card-text">{{news.detail|safe}}</p>
			  </div>
			  <div class="card-footer">
				 <small class="text-muted">Son Güncelleme : {{news.add_time}}</small><br>
				 <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div>
			</div>

			<!-- Yorumlar -->
			<div class="card my-4">
				<h6 class="card-header">Yorum ekle</h6>
				<div class="card-body">
					{% for message in messages %}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Ad<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">E-posta<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Yorum yap<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Önceki Yorumlar -->
			<div class="card my-4">
				<h6 class="card-header">Yorumlar</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title">{{comment.email}}</cite></footer>
					</blockquote>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Alakalı haberler -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">Bu Kategoriden</h3>
			<!-- Kategori Kutusu -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
                <a href="/detail/{{news.id}}"><img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <div class="card-footer">
      				<small class="text-muted">{{news.add_time}}</small>
    			</div>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

Haber_Sitesi_Proje/main/templates/home.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- Öne Çıkan Haberler -->
	<div class="row my-3">
		<!-- Sol Taraf -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <a href="/detail/{{first_news.id}}"><img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}"></a>
			  <div class="card-body">
			    <a href="/detail/{{first_news.id}}"style="text-decoration: none"><h5 class="card-title">{{first_news.title}}</h5></a>
      			  <p class="card-text"><small class="text-muted">{{news.add_time}}</small></p>
		      </div>
			</div>
		</div>
		<!-- Sağ taraf -->
		
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			<h5 class="border-bottom pb-1" style="height:auto">Öne Çıkan Haberler</h5>
			{% for news in three_news %}
			<!-- Haber Kutusu -->
			<div class="card-body">
			  <div class="row no-gutters">
			    <div class="col-md-4">
				<a href="/detail/{{news.id}}"style="text-decoration: none" ><img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}"></a>
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <a href="/detail/{{news.id}}"style="text-decoration: none" ><h6 class="card-title">{{news.title}}</h6></a>
			        <div class="card-footer">
      					<small class="text-muted">{{news.add_time}}</small>
    				</div>
			      </div>
			    </div>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
	{% for category in three_categories %}
	<a href="/category/{{category.id}}"style="text-decoration: none"><h3 class="border-bottom pb-1">{{category.title}}</h3></a>
	<div class="row my-4">
		{% for news in category.news_set.all %}
		  {% if forloop.counter < 5%}
			<!-- Haber Kutusu -->
			<div class="col-md-3">
				<div class="card mb-3 shadow ">
				<a href="/detail/{{news.id}}"style="text-decoration: none"><img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}"></a>
				<div class="card-body-t">
					<a href="/detail/{{news.id}}"style="text-decoration: none"><h6 class="card-title">{{news.title}}</h6></a>
					<div class="card-footer">
      					<small class="text-muted" style="font-size:14px;">{{news.add_time}}</small>
    				</div>
				</div>
				</div>
			</div>
		  {% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	<!--Kategori Sonu-->
</main>
{% endblock %}